/**
 * Demo vault data for users to try the tool
 */
export const DEMO_VAULT = {
    version: 1,
    vault: {
        name: 'Demo Vault',
        logo: 1746441392.391,
        algo: 'AES' as const,
        master: 'demo',
        trash: [
            {
                id: '34',
                login: 'beth_hike',
                password: 'Yv9!zBn4Wp',
                title: 'AllTrails Profile',
                note: 'Premium account',
                url: 'https://alltrails.com',
                created_at: 1714890330234,
                updated_at: 5,
            },
            {
                id: '19',
                login: 'phil_admin',
                password: 'Mw6@xTu7Bc',
                title: 'CPanel Access',
                note: 'For hosting settings',
                url: 'https://cpanel.hosting.com',
                created_at: 1714890180040,
                updated_at: 5,
            },
        ],
        passwords: [
            {
                title: 'Hey you!',
                login: 'ToolKiwi',
                password: '&BNd2L3W1n}FtL;FfOae{%j_',
                url: '',
                note: 'Never share your master password!\n\nThank you for using our tool! <3',
                id: 'maay2fkjb39oqzu2',
                created_at: 1746441315667,
                updated_at: 5,
            },
            {
                id: '1',
                login: 'jane_doe91',
                password: 'Qz7!hT5pEo',
                title: 'My Gmail',
                note: '2FA enabled (FAKE)',
                url: 'https://mail.google.com',
                created_at: 1714890000123,
                updated_at: 1714890000123,
                totp: {
                    secret: '==KEY==',
                    algorithm: 'SHA1' as const,
                    digits: 6,
                    period: 30,
                },
                tag_id: 'mjq1rrulkz',
            },
            {
                id: '2',
                login: 'mark1984',
                password: 'L9#uTx33Km',
                title: 'Amazon Shopping',
                note: '',
                url: 'https://amazon.com',
                created_at: 1714890010100,
                updated_at: 1714890010100,
                tag_id: 'mjq1o332qt',
            },
            {
                id: '3',
                login: 'techfan77',
                password: 'Rw5^dL8zQa',
                title: 'GitHub Profile',
                note: 'Work projects stored',
                url: 'https://github.com',
                created_at: 1714890021000,
                updated_at: 1714890021000,
                totp: {
                    secret: '=KEY=',
                    algorithm: 'SHA1' as const,
                    digits: 6,
                    period: 30,
                },
                tag_id: 'mjq1rrulkz',
            },
            {
                id: '4',
                login: 'emma_writer',
                password: 'Mp2$yTr9Ko',
                title: 'Medium Account',
                note: '',
                url: 'https://medium.com',
                created_at: 1714890030020,
                updated_at: 1714890030020,
            },
            {
                id: '5',
                login: 'sam_gamer',
                password: 'Wz8!eVx0Uu',
                title: 'Steam Games',
                note: 'Remember 2FA app',
                url: 'https://store.steampowered.com',
                created_at: 1714890041000,
                updated_at: 1714890041000,
            },
            {
                id: '6',
                login: 'elena_dev',
                password: 'Br9#fNz6We',
                title: 'Slack Workspace',
                note: '',
                url: 'https://slack.com',
                created_at: 1714890050123,
                updated_at: 1714890050123,
            },
            {
                id: '7',
                login: 'paul_reader',
                password: 'Gn4!oYp7Tq',
                title: 'NYTimes Subscription',
                note: '',
                url: 'https://nytimes.com',
                created_at: 1714890060450,
                updated_at: 1714890060450,
            },
            {
                id: '8',
                login: 'lucy_codes',
                password: 'Xp7@eLm3Vn',
                title: 'LinkedIn Profile',
                note: 'For job search',
                url: 'https://linkedin.com',
                created_at: 1714890070000,
                updated_at: 1714890070000,
            },
            {
                id: '9',
                login: 'harry_music',
                password: 'Ty6^uKo4Wr',
                title: 'Spotify Account',
                note: '',
                url: 'https://spotify.com',
                created_at: 1714890081234,
                updated_at: 1714890081234,
            },
            {
                id: '10',
                login: 'anna_buyer',
                password: 'Zp3#sGj1Nq',
                title: 'eBay Login',
                note: 'Old address still listed',
                url: 'https://ebay.com',
                created_at: 1714890090450,
                updated_at: 1714890090450,
            },
            {
                id: '11',
                login: 'bob_travels',
                password: 'Fq9@hYc6Tp',
                title: 'Airbnb Booking',
                note: '',
                url: 'https://airbnb.com',
                created_at: 1714890100450,
                updated_at: 1714890100450,
            },
            {
                id: '12',
                login: 'claire_blogs',
                password: 'Lu5^xWq3Po',
                title: 'WordPress Site',
                note: 'Blog in French',
                url: 'https://wordpress.com',
                created_at: 1714890110780,
                updated_at: 1714890110780,
            },
            {
                id: '13',
                login: 'michael_netflix',
                password: 'Sq8!vNz2Yt',
                title: 'Netflix Family',
                note: '',
                url: 'https://netflix.com',
                created_at: 1714890120033,
                updated_at: 1714890120033,
            },
            {
                id: '14',
                login: 'nina_fit',
                password: 'Gr7$kBv1Xo',
                title: 'MyFitnessPal',
                note: 'Premium trial',
                url: 'https://myfitnesspal.com',
                created_at: 1714890130670,
                updated_at: 1714890130670,
            },
            {
                id: '15',
                login: 'richard_tweet',
                password: 'Jv3#oKr7Wp',
                title: 'X (formerly Twitter)',
                note: '',
                url: 'https://twitter.com',
                created_at: 1714890140321,
                updated_at: 1714890140321,
                tag_id: 'mjq1o332qt',
            },
            {
                id: '16',
                login: 'lara_admin',
                password: 'Nk2!zGm4Vr',
                title: 'Admin Panel',
                note: 'Internal CMS',
                url: 'https://admin.example.com',
                created_at: 1714890150990,
                updated_at: 1714890150990,
            },
            {
                id: '17',
                login: 'kevin_course',
                password: 'Hx5@dWp9Ls',
                title: 'Udemy Courses',
                note: '',
                url: 'https://udemy.com',
                created_at: 1714890160880,
                updated_at: 1714890160880,
            },
            {
                id: '18',
                login: 'olga_backup',
                password: 'Cq1!fXo6Nr',
                title: 'Dropbox Account',
                note: '',
                url: 'https://dropbox.com',
                created_at: 1714890170122,
                updated_at: 1714890170122,
            },
            {
                id: '20',
                login: 'julie_notes',
                password: 'Yt7#eXp1Ko',
                title: 'Evernote Sync',
                note: '',
                url: 'https://evernote.com',
                created_at: 1714890190000,
                updated_at: 1714890190000,
                totp: {
                    secret: 'KEY',
                    algorithm: 'SHA1' as const,
                    digits: 6,
                    period: 59 as unknown as number,
                },
            },
            {
                id: '21',
                login: 'liam_photo',
                password: 'Bt9!pDr6Mz',
                title: 'Flickr Uploads',
                note: '',
                url: 'https://flickr.com',
                created_at: 1714890200456,
                updated_at: 1714890200456,
            },
            {
                id: '22',
                login: 'nora_team',
                password: 'Uq6$gHv3Lf',
                title: 'Trello Boards',
                note: 'Archived 2023 board',
                url: 'https://trello.com',
                created_at: 1714890210678,
                updated_at: 1714890210678,
                tag_id: 'mjq1o332qt',
            },
            {
                id: '23',
                login: 'david_stream',
                password: 'Rw4^tKs8Bn',
                title: 'Twitch Channel',
                note: '',
                url: 'https://twitch.tv',
                created_at: 1714890220000,
                updated_at: 1714890220000,
            },
            {
                id: '24',
                login: 'mia_travel',
                password: 'Lx3#qPo5Vz',
                title: 'Skyscanner Alerts',
                note: 'Used for EU trip',
                url: 'https://skyscanner.com',
                created_at: 1714890230450,
                updated_at: 1714890230450,
            },
            {
                id: '25',
                login: 'zack_tutor',
                password: 'Nt2!fVr9Qk',
                title: 'Khan Academy',
                note: '',
                url: 'https://khanacademy.org',
                created_at: 1714890240020,
                updated_at: 1714890240020,
            },
            {
                id: '26',
                login: 'julia_movies',
                password: 'Wx5@cLm7Ts',
                title: 'Disney+ Login',
                note: '',
                url: 'https://disneyplus.com',
                created_at: 1714890250123,
                updated_at: 1714890250123,
            },
            {
                id: '27',
                login: 'tom_crypto',
                password: 'Fx9^gDn1Mo',
                title: 'Binance Wallet',
                note: 'Enable withdrawals',
                url: 'https://binance.com',
                created_at: 1714890260543,
                updated_at: 1714890260543,
            },
            {
                id: '28',
                login: 'karen_study',
                password: 'Lq3!uZw0Vp',
                title: 'Coursera Login',
                note: '',
                url: 'https://coursera.org',
                created_at: 1714890270032,
                updated_at: 1714890270032,
            },
            {
                id: '29',
                login: 'leo_booking',
                password: 'Dr7@bZk4Tx',
                title: 'Booking.com',
                note: '',
                url: 'https://booking.com',
                created_at: 1714890280450,
                updated_at: 1714890280450,
            },
            {
                id: '30',
                login: 'amy_hub',
                password: 'Zx6!cLp2Gn',
                title: 'HubSpot CRM',
                note: 'Client emails stored',
                url: 'https://hubspot.com',
                created_at: 1714890290067,
                updated_at: 1714890290067,
            },
            {
                id: '31',
                login: 'vince_dev',
                password: 'Ky4#oQr8Nj',
                title: 'Bitbucket Repo',
                note: '',
                url: 'https://bitbucket.org',
                created_at: 1714890300456,
                updated_at: 1714890300456,
            },
            {
                id: '32',
                login: 'eric_chat',
                password: 'Qp7!lDr3Xt',
                title: 'Discord Server',
                note: '',
                url: 'https://discord.com',
                created_at: 1714890310450,
                updated_at: 1714890310450,
            },
            {
                id: '33',
                login: 'oliver_mail',
                password: 'Az5$kXn6Mo',
                title: 'Yahoo Mail',
                note: '',
                url: 'https://mail.yahoo.com',
                created_at: 1714890320123,
                updated_at: 1714890320123,
            },
            {
                id: '35',
                login: 'jack_codes',
                password: 'Fg6@xRt5Nu',
                title: 'Stack Overflow',
                note: '',
                url: 'https://stackoverflow.com',
                created_at: 1714890340456,
                updated_at: 1714890340456,
            },
            {
                id: '36',
                login: 'lisa_game',
                password: 'Kv2$yWm3Ro',
                title: 'Epic Games',
                note: '',
                url: 'https://epicgames.com',
                created_at: 1714890350789,
                updated_at: 1714890350789,
                tag_id: 'mjq1pb8j5y',
            },
            {
                id: '37',
                login: 'roger_train',
                password: 'Bt8#cGl2Xs',
                title: 'Duolingo',
                note: 'Learning Spanish',
                url: 'https://duolingo.com',
                created_at: 1714890360432,
                updated_at: 1714890360432,
            },
            {
                id: '38',
                login: 'sophie_plan',
                password: 'Zr1@lPf6Vy',
                title: 'Notion Workspace',
                note: '',
                url: 'https://notion.so',
                created_at: 1714890370450,
                updated_at: 1714890370450,
            },
            {
                id: '39',
                login: 'tony_tools',
                password: 'Tq3$eHv5Nj',
                title: 'Canva Design',
                note: '',
                url: 'https://canva.com',
                created_at: 1714890380012,
                updated_at: 1714890380012,
                tag_id: 'mjq1o332qt',
            },
            {
                id: '40',
                login: 'melanie_art',
                password: 'Jx4!rBm7Qz',
                title: 'DeviantArt Login',
                note: 'Portfolio gallery',
                url: 'https://deviantart.com',
                created_at: 1714890390033,
                updated_at: 1714890390033,
                tag_id: 'mjq1pb8j5y',
            },
        ],
        created_at: 1741198615846,
        tags: [
            {
                title: 'Using TOTP',
                color: '#BA55D3',
                id: 'mjq1rrulkz',
                created_at: 1766945570493,
                updated_at: 28,
            },
            {
                title: 'Shared ⚡',
                color: '#00FFFF',
                id: 'mjq1pb8j5y',
                created_at: 1766945455651,
                updated_at: 28,
            },
            {
                title: 'My special tag',
                color: '#FF1493',
                id: 'mjq1o332qt',
                created_at: 1766945398430,
                updated_at: 28,
            },
        ],
    },
    exportedAt: '2025-12-28T18:22:56.763Z',
};
